### ISSUE TITLE
Eta for tutorial posting?

### ISSUE THREAD

**Issue by lessw2020** [abrazinskas/sigir2022-opinion-summarization-tutorial#1]
Very interested and wondering if there is an ETA for the tutorial posting?
Thanks!

**Comment by abrazinskas** [comment]
The tutorial will be presented on the 7th of July -- 11.00 - 14.30 Madrid time.

https://sigir.org/sigir2022/program/tutorials/

**Comment by mshen2** [comment]
Hi, thanks for the great tutorial at SIGIR 2020! Just wondering when the side and video recording can be posted here? Thank you!

**Comment by abrazinskas** [comment]
The slides are already available. The videos will be available soon.
